version: '3.3'

services:

  db:
    image: postgres
    # restart: always
    container_name: pg-kitchen
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty1
