version: '3.3'

services:

  go2-db-pg:
    image: postgres
    # restart: always
    container_name: go2-pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty1
      POSTGRES_DB: go2
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  go2-pg-admin:
    image: dpage/pgadmin4
    container_name: go2-pg-admin
    # restart: always
    ports:
      - "5451:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: qwerty1

  go2-manager:
    build:
      context: ./manager
#      dockerfile: ./manager/Dockerfile
    container_name: go2-manager
    ports:
      - "9010:9010"
    environment:
      DOT_ENV_FILE_NAME: docker.env
    depends_on:
      go2-db-pg:
        condition: service_healthy


