uri: amqp://guest:guest@localhost:5672/
queues:
  - name: test2
    durable: true
    autoDelete: false
    persistent: true
  - name: readyOrders
    durable: true
    autoDelete: false
    persistent: true